
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff', paddingHorizontal: 16, paddingTop: 12 },
  heading: { fontSize: 18, fontWeight: '600', marginBottom: 10, color: '#222' },
  subheading: { fontSize: 12, color: '#c0392b', marginBottom: 14 },
  header: { fontSize: 26, fontWeight: '400', color: '#222' },
  tabs: { flexDirection: 'row', marginBottom: 14 },
  tabText: { fontSize: 14, color: '#999', marginRight: 18, paddingBottom: 6 },
  tabTextActive: { color: '#222', fontWeight: '600', borderBottomWidth: 2, borderBottomColor: '#2f6fed' },
  itemCard: {
    flexDirection: 'row',
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  itemImage: {
    width: 70,
    height: 70,
    backgroundColor: '#222',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    overflow: 'hidden',
  },
  itemImageText: { color: '#fff', fontSize: 13 },
  itemImagePhoto: { width: '100%', height: '100%' },
  itemInfo: { flex: 1, justifyContent: 'center' },
  itemName: { fontSize: 14, color: '#222', marginBottom: 2 },
  itemPrice: { fontSize: 13, color: '#444', marginBottom: 8 },
  itemLine: { fontSize: 13, color: '#444' },
  noteLine: { fontSize: 12, color: '#777', marginTop: 2 },
  selectBtn: { backgroundColor: '#4caf50', borderRadius: 6, paddingVertical: 8, alignItems: 'center' },
  selectBtnText: { color: '#fff', fontWeight: '600', fontSize: 13 },
  summaryBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#333',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  summaryText: { color: '#fff', fontSize: 13 },
  submitBtn: { backgroundColor: '#2f6fed', borderRadius: 6, paddingVertical: 8, paddingHorizontal: 16 },
  submitBtnText: { color: '#fff', fontWeight: '600', fontSize: 13 },
  emptyText: { fontSize: 14, color: '#888', marginTop: 20, textAlign: 'center' },
  total: {
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'right',
    color: '#222',
    position: 'absolute',
    bottom: 66,
    right: 16,
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#333',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 14,
  },
  navText: { color: '#fff', fontSize: 13 },
  cancelBtn: { flex: 1, backgroundColor: '#888', paddingVertical: 16, alignItems: 'center' },
  cancelText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  confirmBtn: { flex: 1, backgroundColor: '#2f6fed', paddingVertical: 16, alignItems: 'center' },
  confirmBtnDisabled: { backgroundColor: '#a9c2f2' },
  confirmText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  itemHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  statusBadge: {
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    overflow: 'hidden',
    color: '#fff',
  },
  status_waiting: { backgroundColor: '#f39c12' },
  status_cooking: { backgroundColor: '#2f6fed' },
  status_served: { backgroundColor: '#27ae60' },
  status_cancelled: { backgroundColor: '#aaaaaa' },
  cancelBtnText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  receipt: { flex: 1, marginBottom: 60 },
  line: { fontFamily: 'monospace', fontSize: 13, color: '#222', lineHeight: 20 },
  cancelledLine: { textDecorationLine: 'line-through', color: '#999' },
  roundHeader: { fontFamily: 'monospace', fontSize: 13, color: '#222', marginTop: 10, fontWeight: '600' },
  divider: { fontFamily: 'monospace', fontSize: 13, color: '#222', marginTop: 10 },
  grandTotal: { fontFamily: 'monospace', fontSize: 15, fontWeight: '700', color: '#222', marginTop: 4 },
  selectedPreview: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  selectedImage: { width: 56, height: 56, borderRadius: 8 },
  placeholderImage: { width: 56, height: 56, borderRadius: 8, backgroundColor: '#dfe7f5', alignItems: 'center', justifyContent: 'center' },
  placeholderText: { fontSize: 12, color: '#555' },
  selectedName: { fontSize: 16, fontWeight: '600', color: '#222', marginLeft: 12 },
});