// src/data/menuData.js
// รูปร่างข้อมูลตรงกับตาราง categories / menu_items ใน schema.sql
// ตอนนี้ทั้งสองตารางใน restaurent.db ยังไม่มีข้อมูล เลยใช้ไฟล์นี้ทำหน้า UI ไปก่อน
// พอพร้อมค่อยสลับไป query จาก SQLite จริง โดยคง field name ให้ตรงกับคอลัมน์เดิม
// เพื่อสลับ source ทีหลังได้ง่าย (แค่เปลี่ยนที่ import ใน MennuScreen.js)
//
// image: ใส่เป็นลิงก์รูป (URL string) ได้เลย เช่น 'https://.../pad-kra-pao.jpg'
// ไม่มีคอลัมน์นี้ใน schema.sql ตอนนี้ — ถ้าจะเก็บรูปจริงในฐานข้อมูลทีหลัง
// ต้องเพิ่มคอลัมน์ image_url (TEXT) ลงตาราง menu_items ก่อน

export const CATEGORIES = [
  { category_id: 1, name: 'อาหาร', is_active: 1 },
  { category_id: 2, name: 'เครื่องดื่ม', is_active: 1 },
  { category_id: 3, name: 'ก๋วยเตี๋ยว', is_active: 1 },
  { category_id: 4, name: 'ของหวาน', is_active: 1 },
];

// addon เป็นข้อมูลเสริมฝั่ง UI เท่านั้น (schema ไม่มีตาราง addon แยก)
// ตอนยืนยัน จะถูกอัดรวมเป็นราคา (unit_price) + คำอธิบาย (note) ให้ตรงกับ order_items
export const MENU_ITEMS = [
  {
    menu_item_id: 1,
    category_id: 1,
    name: 'ข้าวผัดกะเพรา',
    price: 50,
    is_available: 1,
    image: 'https://cdn-ildplgb.nitrocdn.com/IsDIEVbKqjLKLwSjgUBetWWfJLAUdaLp/assets/images/optimized/rev-11c5d90/www.thammculture.com/wp-content/uploads/2024/01/Untitled-612.jpg',
    addon: {
      meatOptions: ['หมู', 'ไก่', 'กุ้ง', 'เนื้อ'],
      extras: [
        { label: 'ไข่ดาว', price: 10 },
        { label: 'ไข่เจียว', price: 10 },
        { label: 'เพิ่มข้าว', price: 10 },
      ],
    },
  },
  {
    menu_item_id: 2,
    category_id: 1,
    name: 'ข้าวผัดพริกแกง',
    price: 50,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-ek-bZCSOH9t-eKgFiB3hWshAoWanBIUxZjgwZa5rtlt36QwmIEsAcQOj&s=100',
    addon: {
      meatOptions: ['หมู', 'ไก่', 'กุ้ง'],
      extras: [
        { label: 'ไข่ดาว', price: 10 },
        { label: 'ไข่เจียว', price: 10 },
      ],
    },
  },
  {
    menu_item_id: 3,
    category_id: 1,
    name: 'ข้าวผัดผงกระหรี่',
    price: 50,
    is_available: 1,
    image: 'https://i.pinimg.com/736x/25/59/94/2559942c3ccfab98f5e448f325226cab.jpg',
    addon: { meatOptions: ['หมู', 'ไก่', 'กุ้ง'], extras: [{ label: 'ไข่ดาว', price: 10 }] },
  },
  {
    menu_item_id: 4,
    category_id: 1,
    name: 'ข้าวผัด',
    price: 50,
    is_available: 1,
    image: 'https://www.nestleprofessional.co.th/sites/default/files/styles/np_recipe_detail/public/2022-04/resive_04062021_430x320px-2_0.png?itok=IVRT5J1c',
    addon: { meatOptions: ['หมู', 'ไก่', 'กุ้ง'], extras: [{ label: 'ไข่ดาว', price: 10 }] },
  },
  {
    menu_item_id: 5,
    category_id: 1,
    name: 'ข้าวคะน้า',
    price: 50,
    is_available: 1,
    image: 'https://fit-d.com/uploads/food/afb11fe696d53169c7bce688ab5010c1.jpg',
    addon: { meatOptions: ['หมู', 'ไก่', 'กุ้ง'], extras: [] },
  },
  {
    menu_item_id: 6,
    category_id: 2,
    name: 'โค้ก',
    price: 20,
    is_available: 1,
    image: 'https://st.bigc-cs.com/cdn-cgi/image/format=webp,quality=90/public/media/catalog/product/11/88/8855199632011/8855199632011_2-20240606193806-.webp',
    addon: { bottleOptions: ['ขวด', 'โปร', 'ทาวเวอร์', 'แก้ว'] },
  },
  {
    menu_item_id: 9,
    category_id: 2,
    name: 'น้ำเปล่า',
    price: 10,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuPS-DBvhF5sIMvGR1cT9SoTyJ2KKUTphiAwcDkw6GPA&s=10',
    addon: { bottleOptions: ['ขวดเล็ก', 'ขวดใหญ่'] },
  },
  {
    menu_item_id: 10,
    category_id: 2,
    name: 'น้ำแดง',
    price: 20,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8LaUjqaOh7orhrDyQ2Gzb3W9ZlCLVJXfYBIYNsrQPlw&s=10',
    addon: { bottleOptions: ['ขวด', 'แก้ว'] },
  },
  {
    menu_item_id: 11,
    category_id: 2,
    name: 'ชาเย็น',
    price: 30,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaF6OIoyBGY8yoE53DewmwEr3j_8pAAuYlspvfnuhWYg&s=10',
    addon: { serveOptions: ['หวานปกติ', 'หวานน้อย'], extras: [{ label: 'เพิ่มไข่มุก', price: 10 }] },
  },
  {
    menu_item_id: 12,
    category_id: 2,
    name: 'กาแฟเย็น',
    price: 35,
    is_available: 1,
    image: 'https://www.nestleprofessional.co.th/sites/default/files/styles/np_recipe_detail/public/2022-04/nescafe-iced-signature-540x400.jpg?itok=5gl_au1G',
    addon: { serveOptions: ['หวานปกติ', 'หวานน้อย'] },
  },
  {
    menu_item_id: 7,
    category_id: 3,
    name: 'ก๋วยเตี๋ยวต้มยำ',
    price: 45,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYHQUIWpJNPAwAiuPMZsmhPjotMte8A93H6frIfx5Xeg&s=10',
    addon: { meatOptions: ['หมู', 'ไก่', 'ลูกชิ้น'], extras: [{ label: 'เส้นเพิ่ม', price: 10 }] },
  },
  {
    menu_item_id: 13,
    category_id: 3,
    name: 'ก๋วยเตี๋ยวน้ำใส',
    price: 45,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9NLETqHt5DrqZU9L13tkJGk5nxUZUr5hrPNSrAuDndA&s=10',
    addon: { meatOptions: ['หมู', 'ไก่', 'ลูกชิ้น'], extras: [{ label: 'เส้นเพิ่ม', price: 10 }] },
  },
  {
    menu_item_id: 14,
    category_id: 3,
    name: 'เย็นตาโฟ',
    price: 50,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6laZvUl2BpxEFT7UXFIgm0p4BrjiDzhEqqQfxbNb4Qw&s=10',
    addon: { meatOptions: ['หมู', 'ไก่', 'ทะเล'], extras: [{ label: 'เกี๊ยวทอด', price: 10 }] },
  },
  {
    menu_item_id: 15,
    category_id: 3,
    name: 'บะหมี่เกี๊ยว',
    price: 50,
    is_available: 1,
    image: 'https://img.wongnai.com/p/256x256/2023/01/19/ca34841db81f4924824f144f2bcb9983.jpg',
    addon: { meatOptions: ['หมู', 'ไก่'], extras: [{ label: 'เกี๊ยวเพิ่ม', price: 15 }] },
  },
  {
    menu_item_id: 16,
    category_id: 3,
    name: 'ราดหน้า',
    price: 50,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREKPsaeDxi0x7FeXueuWMe8GXUDuumylPlUkuvOyLw1g&s=10',
    addon: { meatOptions: ['หมู', 'ไก่', 'ทะเล'], extras: [{ label: 'เพิ่มไข่', price: 10 }] },
  },
  {
    menu_item_id: 8,
    category_id: 4,
    name: 'ไอศกรีม',
    price: 30,
    is_available: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAd2EWSA6uUBSSeOukrQ2aw81ULDIezuE_KXGUTB7BnA&s=10',
    addon: { serveOptions: ['เสิร์ฟทีหลัง', 'เสิร์ฟทันที'] },
  },
  {
    menu_item_id: 17,
    category_id: 4,
    name: 'ข้าวเหนียวมะม่วง',
    price: 60,
    is_available: 1,
    image: 'https://blog.hungryhub.com/wp-content/uploads/2022/04/fresh-ripe-mango-sticky-rice-with-coconut-milk-dark-surface-1024x683.jpg',
    addon: { serveOptions: ['เสิร์ฟทันที', 'แยกกะทิ'] },
  },
  {
    menu_item_id: 18,
    category_id: 4,
    name: 'บัวลอย',
    price: 35,
    is_available: 1,
    image: 'https://img.kapook.com/u/2022/wanwanat/1079595941.jpg',
    addon: { serveOptions: ['ร้อน', 'เย็น'] },
  },
  {
    menu_item_id: 19,
    category_id: 4,
    name: 'ลอดช่อง',
    price: 35,
    is_available: 1,
    image: 'https://www.ryoiireview.com/upload/article/201703/1490859322_ad1f17c1703feed1aa9f266d2ebcc056.jpg',
    addon: { serveOptions: ['หวานปกติ', 'หวานน้อย'] },
  },
  {
    menu_item_id: 20,
    category_id: 4,
    name: 'เฉาก๊วยนมสด',
    price: 40,
    is_available: 1,
    image: 'https://i.pinimg.com/474x/3f/ab/5e/3fab5e436f917d68d79aae673e73f916.jpg',
    addon: { serveOptions: ['หวานปกติ', 'หวานน้อย'], extras: [{ label: 'เพิ่มไข่มุก', price: 10 }] },
  },
];